### ISSUE TITLE
As a user I should be able to access a budget and edit the budget items

### ISSUE THREAD

**Issue by zacck** [LittleKidogo/MoneyLog#2]
# **Feature/Fix**
This is a proposed feature to replace the functionality we currently place in the budget sheet. The aim of this is to get a standardized recording of all we intend to spend on.

# **Current Situation**
Currently whenever we need a new budget mostly when starting a new period where we have to budget for we allocate chunks of money to different sectors such as `internet`, `food`,`communication`. What happens is we use a copy of the existing sheet and update it with the items we perceive we will need to spend on.
I suggest a section in the system where as a user I will be able to `chunk` out the proposed expenditure for a fiscal period.
Items should have the following details 
- [ ] Item Name
- [ ] Due Date 
- [ ] Comments 
- [ ] Category of expense

# **Acceptance Criteria**
A user should be able to access and edit a budget's chunk spend and allocation of resources

**Comment by zacck-zz** [comment]
@cybot1711  @CIEspost  Exposing this on the graphql API today, we need a client soon!

**Comment by zacck-zz** [comment]
# Notes
On the backend, this includes exposing this entails exposing the functionality in the wishlist context here we would have  
- [x] query list all wishlist items associated to a budget 
- [x] mutation to add a wishlist item 
- [x] mutation to update a wishlist item
