### ISSUE TITLE
Create Model for PurchaseItem

### ISSUE THREAD

**Issue by zacck** [LittleKidogo/MoneyLog#22]
A PurchaseItem is used to record an instance of when an Item is purchased the schema for this is also used for a WantsItem which is the draft used to create a PurchaseItem. A PurchaseItem Contains the following fields 
- name: name of the item
- id: system generated id of the item 
- type: type this is the PaymentMethod planned for this Purchase
- qpm: this is the number of times this item purchased per a budget this if 1 it would be allocated to the first section if more than one a user needs to select one or more sections for the item 
- category: This is the LogCategory this item belongs to 
- price: this is the price as planned for this item 
- location: this is the planned location of purchase for this item 

seeing as this will also be used for the WantsItem model two sets of tests will be described 

# Wants Tests 
- [ ] Create a WantsItem if name is provided 
- [ ] Update a WantsItems name, qpm, price,location, type
- [ ] Delete a WantsItem
# Purchase Tests
- [ ] Convert WantsItem to PurchaseItem if 1 qpm then select a Logsection for the item the default being the first  if more than 1 select 1 or more sections for the item(s)
- [ ] Update PurchasItems name, qpm, price, location, type  provided the MoneyLog isn't refined

**Comment by zacck-zz** [comment]
WantsItems and PurchaseItems are the same things really it's just that a purchase item has been assigned to a budget section actually the name here is confusing they are both a wishlist items
