### ISSUE TITLE
As a user I need the ability to record and review expenses as I spend

### ISSUE THREAD

**Issue by zacck** [LittleKidogo/MoneyLog#3]
# **Feature/Fix**
This is a proposed feature. As a user I need to record my expenses as I go through the budget period. 

# **Current Situation**
Currently we add expenses in a sheet in the doc, What would be awesome is if when one is logging an expense it could get tagged with a budget chunk and also linked to shopping list item if one exists. This would help in finegrained observation of expenses.
I propose that the functionality for the expenses function as the described in the flow chart below

![img_2719](https://user-images.githubusercontent.com/897731/31074662-fc9aefa8-a771-11e7-93b0-e4d0428c0f3b.JPG)
These details are what should be collected for an expense item 

- [ ] Date Spents 
- [ ] Item Name
- [ ] Item Cost 
- [ ] Type of Expenditure (whether is personal, or for a project)
- [ ] Category of Expenditure (As determined from the budget)
- [ ] Payment type used
- [ ] Comments if any

# **Acceptance Criteria**
As a user I should be able to log expenses tagged with category and type details.

**Comment by zacck-zz** [comment]
Closing this issue as it belongs to the Front end
