### ISSUE TITLE
As a user I should be able to add an Item to a shopping list for purchasing

### ISSUE THREAD

**Issue by zacck** [LittleKidogo/MoneyLog#4]
# **Feature/Fix**
This proposal is for a feature, As a user running my budget that I have on the application. I am likely discovering and allocating items to spend resources on

# **Current Situation**
At the moment as soon as we can after we spend, we will usually add the details of our expenditure on the expenses sheet in a budget document. I am proposing we adapt this too however this should likely be an action button with the details likely left for the reports section. 
When recording an expense a user should be able to record the following details of an expense 
- [ ] Item Name
- [ ] Item Price
- [ ] Where to find item(  site, shop)
- [ ] Category 
- [ ] Type of Expenditure the item will be 

# **Acceptance Criteria**
A user should be able to appropriately record an item so it can be spent on.

**Comment by zacck-zz** [comment]
The functionality described here is covered in #2
