### ISSUE TITLE
As a user I need to access reports for different kinds of stats in a MoneyLog

### ISSUE THREAD

**Issue by zacck** [LittleKidogo/MoneyLog#6]
# **Feature/Fix**
This is a feature proposal. The main reason we decided to work on this application is due to the fact that we need to pull a certain number and types of reports from recording all these items. These reports should aid in making adjustments to the money operations enabling us to meet criteria set for fiscal periods

# **Current Situation** 
At the moment we are struggling with this section as we cant really generate reports with the current system we are using. A number of formulas are required all dependent on other formulas this is seen as a simpler solution.
The following is a list of reports that would be needed among others

- [ ]  How much is currently spent on a category vs the amount budgeted
- [ ] Reports for total Earnings 
- [ ] Reports for total spending 
- [ ] Due items (things close to being paid for)

# **Acceptance Requirements**

A user should be able to explore reports for fiscal periods/budgets

**Comment by zacck-zz** [comment]
Closing this issue as it belongs to the Front End
