### ISSUE TITLE
Move to Graphql

### ISSUE THREAD

**Issue by zacck** [LittleKidogo/MoneyLog#61]
## Expected Behavior
The app is currently designed as a rest api however seeing as this is pretty greenfield project how about we leverage graphql from the get go.

## Actual Behavior
We currently serialize our views into json, we would likely replace these with graphql mutations

## Acceptance Criteria
App should be using Graphql
## Steps to Reproduce the Problem

  1.

## Specifications

  - Version:

**Comment by zacck-zz** [comment]
In order for us to achieve this, we will need to implement a number of items
- [x] context-based authentication for our API
- [x] Transfer user controller actions to a user resolver #80 
- [x] Get rid of unused controllers and views 
- [x] Create a graphql schema & endpoint #79
